name: LevelUp
author: jonadead
main: fr.jonadead.LevelUp.LevelUp
version: 1.0
commands:
  reload levelup:
    description: Pour reload le plugin.
    usage: /<command>
  level [player]:
    description: Pour voir votre niveau ou celui d'un joueur.
    usage: /<command> [player]
  level set [player] <level>:
    description: Pour vous assigner un level ou a un autre joueur.
    usage: /<command> [player] <level>
  levelup [player]:
    description: Pour vous augmenter d'un level ou un autre joueur.
    usage: /<command> [player]
  leveldown [player]:
    description: Pour vous diminuer d'un level ou un autre joueur.
    usage: /<command> [player]
  xp [player]:
    description: Pour voir votre xp ou celui d'un autre joueur.
    usage: /<command> [player]